language: php

php:
    - 8.0
    - 8.1
    - 8.2

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=6.0 WP_MULTISITE=0
    - WP_VERSION=6.0 WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
